[tasks.default]
alias = "build-all"

[tasks.build-all]
dependencies = ["doc", "build"]

[tasks.doc]
command = "cargo"
args = ["doc", "--bins", "--no-deps"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]


[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clippy"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.update]
dependencies = ["cargo-update"]

[tasks.cargo-update]
command = "cargo"
args = ["update"]

[tasks.release]
command = "cargo"
args = ["release"]
