[tasks.default]
alias = "build-all"

[tasks.build-all]
dependencies = ["doc", "build", "build-platforms"]
run_task = "dist"

[tasks.doc]
command = "cargo"
args = ["doc", "--bins", "--no-deps"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.build-platforms]
command = "cargo"
args = [
    "zigbuild", "--release",
    "--target", "aarch64-apple-darwin",
    "--target", "aarch64-unknown-linux-musl",
    "--target", "x86_64-apple-darwin",
    "--target", "x86_64-pc-windows-gnu",
    "--target", "x86_64-unknown-linux-musl",
]

[tasks.dist]
script_runner = "@shell"
script = '''
tar caf dist/moove-apple-aarch64.tar.gz  -C target/aarch64-apple-darwin/release       moove 
tar caf dist/moove-linux-aarch64.tar.gz  -C target/aarch64-unknown-linux-musl/release moove 
tar caf dist/moove-apple-x86_64.tar.gz   -C target/x86_64-apple-darwin/release        moove       
tar caf dist/moove-linux-x86_64.tar.gz   -C target/x86_64-unknown-linux-musl/release  moove  
tar caf dist/moove-windows-x86_64.tar.gz -C target/x86_64-pc-windows-gnu/release      moove.exe 
'''

[tasks.setup]
command = "rustup"
args = [
    "target", "add",
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-gnu",
    "x86_64-unknown-linux-musl"
]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clippy"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.update]
dependencies = ["cargo-update", "cargo-upgrade"]

[tasks.cargo-update]
command = "cargo"
args = ["update"]

[tasks.cargo-upgrade]
command = "cargo"
args = ["upgrade"]

