name: Publish WinGet

on:
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  winget:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: Urin.moove
          installers-regex: '\.zip$'
          release-tag: ${{ github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}
